#!/usr/bin/env bash
# create-ai-cli installer — writes a launcher at ~/.local/bin/create-ai-cli
# pointing at this clone. Edits to src/create_ai_cli/ take effect immediately.
# No reinstall needed.
#
# The canonical way to run create-ai-cli is `pipx run create-ai-cli <name>`.
# This script exists for the curl-install path and local development.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAUNCHER_DIR="${HOME}/.local/bin"
LAUNCHER="${LAUNCHER_DIR}/create-ai-cli"

mkdir -p "${LAUNCHER_DIR}"

cat > "${LAUNCHER}" <<EOF
#!/usr/bin/env bash
# auto-generated by create-ai-cli install.sh
exec python3 -c "import sys; sys.path.insert(0, '${REPO_ROOT}/src'); from create_ai_cli.cli import main; sys.exit(main())" "\$@"
EOF

chmod +x "${LAUNCHER}"

echo "✓ Installed create-ai-cli → ${LAUNCHER}"
echo ""

if ! command -v create-ai-cli >/dev/null 2>&1; then
  echo "⚠ ${LAUNCHER_DIR} is not on your PATH."
  echo "  Add this to your shell profile (~/.zshrc or ~/.bashrc):"
  echo ""
  echo "    export PATH=\"\$HOME/.local/bin:\$PATH\""
  echo ""
  echo "  Then reload your shell."
  echo ""
fi

echo "Try it:  create-ai-cli --version"
echo "         create-ai-cli --help"
