#!/usr/bin/env bash
# aiscaffold installer — writes a launcher at ~/.local/bin/aiscaffold
# pointing at this clone. Edits to src/aiscaffold/ take effect immediately.
# No reinstall needed.
#
# The canonical way to run aiscaffold is `pipx run aiscaffold <name>`.
# This script exists for the curl-install path and local development.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAUNCHER_DIR="${HOME}/.local/bin"
LAUNCHER="${LAUNCHER_DIR}/aiscaffold"

mkdir -p "${LAUNCHER_DIR}"

cat > "${LAUNCHER}" <<EOF
#!/usr/bin/env bash
# auto-generated by aiscaffold install.sh
exec python3 -c "import sys; sys.path.insert(0, '${REPO_ROOT}/src'); from aiscaffold.cli import main; sys.exit(main())" "\$@"
EOF

chmod +x "${LAUNCHER}"

echo "✓ Installed aiscaffold → ${LAUNCHER}"
echo ""

if ! command -v aiscaffold >/dev/null 2>&1; then
  echo "⚠ ${LAUNCHER_DIR} is not on your PATH."
  echo "  Add this to your shell profile (~/.zshrc or ~/.bashrc):"
  echo ""
  echo "    export PATH=\"\$HOME/.local/bin:\$PATH\""
  echo ""
  echo "  Then reload your shell."
  echo ""
fi

echo "Try it:  aiscaffold --version"
echo "         aiscaffold --help"
